[package]
name = 'structr'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'structr'

[dependencies]
extendr-api = { version = '0.8', features = ["result_condition"] }
hashbrown = "0.15.2"
serde = "1.0.219"
simd-json = "0.14.3"
