[package]
name = 'structr'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'structr'

[dependencies]
extendr-api = { version = '0.8', features = ["result_condition"] }
serde = "1.0.219"
serde_json = "1.0.140"
