# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_structr_wrappers", use_symbols = TRUE, package_name = "structr")

#' @usage NULL
#' @useDynLib structr, .registration = TRUE
NULL

#' Parses a JSON string according to a provided structure definition using streaming.
#'
#' @param json_string A character string containing the JSON data.
#' @param structure An R list object representing the structure, created by `build_structure()`.
#' @return An R object (list, vector, atomic) representing the parsed JSON if validation succeeds.
#' @ Rtype R_parse_json(json_string: String, structure: list) -> Robj
#' @export
parse_json_impl <- function(json_string, structure) .Call(wrap__parse_json_impl, json_string, structure)

Structure <- new.env(parent = emptyenv())

Structure$convert_from_robj <- function(value) .Call(wrap__Structure__convert_from_robj, value)

#' @export
`$.Structure` <- function (self, name) { func <- Structure[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Structure` <- `$.Structure`


# nolint end
