# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_structr_wrappers", use_symbols = TRUE, package_name = "structr")

#' @usage NULL
#' @useDynLib structr, .registration = TRUE
NULL

parse_json_impl <- function(json_string, structure) .Call(wrap__parse_json_impl, json_string, structure)

serialize_structure <- function(structure, data) .Call(wrap__serialize_structure, structure, data)

serialize_structure_pretty <- function(structure, data) .Call(wrap__serialize_structure_pretty, structure, data)

Structure <- new.env(parent = emptyenv())

Structure$print <- function() invisible(.Call(wrap__Structure__print, self))

Structure$convert_from_robj <- function(value) .Call(wrap__Structure__convert_from_robj, value)

#' @export
`$.Structure` <- function (self, name) { func <- Structure[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Structure` <- `$.Structure`


# nolint end
